name: "Github pages APT repo"
description: "Setup and manage APT repo on Github pages"
inputs:
  repo_supported_arch:
    description: "Newline-delimited list of supported architecture"
    required: true
  repo_supported_version:
    description: "Newline-delimited list of supported (linux) version"
    required: true
  file:
    description: "Newline-delimited list of .deb files"
    required: true
  file_target_version:
    description: "Newline-delimited list of version target of supplied .deb file"
    required: true
  public_key:
    description: "GPG public key for apt repo"
    required: false
  private_key:
    description: "GPG private key for signing apt repo"
    required: true
  key_passphrase:
    description: "Passphrase of GPG private key"
    required: false
  repo_folder:
    description: "Location of APT repo folder relative to root of Github pages"
    required: false
    default: "repo"
  debug:
    description: "Print debug log"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "upload-cloud"
  color: "red"
